### ISSUE TITLE
[Feature Request]: Custom NavigationButton Component

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Frontend#24]
### Is your feature request related to a problem? Please describe.

Our website will have multiple buttons similar to https://homy-next.vercel.app/ 
All those buttons can majorly be categorised as two types of element `button` and `a` tag. 
We will use `a` tag when we are navigating from one-page to another-page (internal or external).
We will use `button` tag when are actually do some algorithmic work like making an API call, etc.

Note: Don't get confused because of looks. The UI of an `a` tag and a `button` tag can be same.
Note: In React, we can use `Link` tag too instead of `a` tag which we will finalise while working on the actual PR.

So based on this theory we want to create NavigationButton component and use it effectively.

### Describe the solution you'd like

There are multiple types of Navigation buttons which you can see here https://homy-next.vercel.app/
We need to focus on creating NavigationButton component which supports these elements:

| Default | Hover |
|--------|--------|
| <img width="162" alt="Screenshot 2024-08-22 at 11 35 58 AM" src="https://github.com/user-attachments/assets/575a9d3f-05ab-4b65-990d-91c9708410c5"> | <img width="145" alt="Screenshot 2024-08-22 at 11 37 04 AM" src="https://github.com/user-attachments/assets/117395df-f222-48eb-8a1d-bcf343c80036"> |
| <img width="195" alt="Screenshot 2024-08-22 at 11 36 02 AM" src="https://github.com/user-attachments/assets/17670ac3-23e1-427a-8aa8-1f5bd883a8c5"> | <img width="192" alt="Screenshot 2024-08-22 at 11 37 08 AM" src="https://github.com/user-attachments/assets/6dc86ea7-f367-40f7-af0e-1dc811fae47f"> |
| <img width="170" alt="Screenshot 2024-08-22 at 11 36 09 AM" src="https://github.com/user-attachments/assets/98649f2a-bba9-4ed5-8cac-d43f76ede598"> | <img width="168" alt="Screenshot 2024-08-22 at 11 37 14 AM" src="https://github.com/user-attachments/assets/bb1692e5-ab5b-4243-9b94-ff39f2d06f94"> |
| <img width="62" alt="Screenshot 2024-08-22 at 11 36 20 AM" src="https://github.com/user-attachments/assets/15430ab6-d5a4-47c6-bb73-d004411051ec"> | <img width="63" alt="Screenshot 2024-08-22 at 11 37 21 AM" src="https://github.com/user-attachments/assets/8c7974ba-1184-4426-bd4f-bf1432960aed"> |

You can get exact details of margin, padding, roundness, etc by inspecting the element on the website link.

Reference video of how to create a component: https://youtu.be/Z6Dj-Ma_ENs?t=2638

Suggestion: Focus on creating a component with `Link` tag just of one button first. Also you can handle this issue in multiple PRs.

### Checklist
- [ ] Default NavigationButton similar to `Add Listing`
- [ ] Outline NavigationButton similar to `Login` or `Meet Entire Team`
- [ ] Black NavigationButton similar to `Search` and arrow
- [ ] Add NavigationButton with various configurations to storybook

**Comment by rray524** [comment]
@ankithacherian can I work on this? it is not worked yet since last month.

**Comment by ankithacherian** [comment]
Hey hi @rray524 ,yes pls re assign to your name if you want to work on this.
