### ISSUE TITLE
[Feature Request]: Custom SocialLink component

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Frontend#26]
### Is your feature request related to a problem? Please describe.

We need to add elements for social links like facebook, instagram, etc.

### Describe the solution you'd like

Design: https://homy-next.vercel.app/ (Bottom most part of the page)
<img width="201" alt="Screenshot 2024-08-22 at 12 06 54 PM" src="https://github.com/user-attachments/assets/4f7b3cb2-6873-46a2-b416-7e6a88dfa231">

Implement there hover design too.

Name the component as `SocialLink` which should be reusable.

Add this component to storybook.

**Comment by rohit-simbanic** [comment]
I will work on this today

**Comment by vanamraghu** [comment]
I will work on this, thanks @aniketpatidar
