### ISSUE TITLE
[Feature Request]: Add Color palette to Website

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Frontend#29]
### Is your feature request related to a problem? Please describe.

We need proper color palette for our website

### Describe the solution you'd like

Colors from this website: https://fonts.google.com/specimen/Open+Sans

| Color Name | Color Code |
|--------|--------|
| orange | #ff6725 |
| orange-dark | #ff3f25 |
| orange-light | #fef7f3 |
| brown | #453a34 |
| green | #00b579 |

**Comment by KvngJamesNG** [comment]
![image](https://github.com/user-attachments/assets/f101c3a4-ef90-4555-80fe-7a7918ab6090)

@rt4914 see the attached image


also you didn't review the code, because I have fixed the issue.

I just wrote the comment above to ask questions about my curiosity generally.
