### ISSUE TITLE
Social Icons should open in next tab

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Frontend#52]
### Describe the bug

There are SocialLink/Icon based component which redirects the page to proper social page like instagram. Ideally these icons when clicked should be opened in a separate tab.

### Steps To Reproduce

1. In terminal start storybook `yarn storybook`
2. Go to socialLink / socialIcon
3. Click on Facebook / Instagram

Notice that it opens in current tab only

### Expected Behavior

The social page should open in a separate tab.

**Comment by vanamraghu** [comment]
I will work on this bug
