### ISSUE TITLE
Add tailwind css to project

### ISSUE THREAD

**Issue by rt4914** [rt4914/KlinicCon-Frontend#7]
Add tailwind css to project

**Comment by Avinashshiyani** [comment]
i can add tailwind css to project .

**Comment by rt4914** [comment]
Hey @Avinashshiyani 
Thanks for showing interest

Unfortunately we are not accepting any open-source contributions yet. This project is for my [Youtube Community Members](https://www.youtube.com/@rtcodes) only who showed interest in learning React and Ruby on Rails.

So currently its not open for everyone, but if you still need to learn new things, you can subscribe to the channel and fill out this form so that I will reach out to you whenever I start the new batch https://forms.gle/h1EfZNBYQT1b9HpY6
